### ISSUE TITLE
Problem with with Str limit function

### ISSUE THREAD

**Issue by octarino** [Usbac/wolff-framework#1]
`echo Str::limit('ññññññ', 3);`

This returns 

> ñ�

`echo Str::limit('ññññññ', 2);`

> ñ

`echo Str::limit('ññññññ', 1);`

> �

Check this for reference

https://github.com/illuminate/support/blob/14b167f5669286cb2d410a4a28eb68858df4852c/Str.php#L281

**Comment by Usbac** [comment]
Thank you so much for pointing out that @octarino, It has been fixed 345a225 :)
Greetings.
