### ISSUE TITLE
DB::Count() is not compatible with all DB drivers

### ISSUE THREAD

**Issue by farfromunique** [Usbac/wolff-framework#10]
The function[ DB::count() ](https://github.com/Usbac/wolff-framework/blob/e16c573235d180f59d46e373b94fccdfa5213688/src/Core/DB.php#L309-L327) assumes that a query including `COUNT(*)` in the `SELECT` will return a column named `COUNT(*)`. This is not true in all database drivers! In Postgres, the column will be named `count`. In MSSQL, the column will be `unknown` (IIRC).

**Comment by Usbac** [comment]
Fixed, thank you so much!
