### ISSUE TITLE
Undefined variable $pdo in class DB

### ISSUE THREAD

**Issue by octarino** [Usbac/wolff-framework#3]
`352    Undefined variable: $pdo`
`353    Undefined variable: $pdo`

https://github.com/Usbac/wolff-framework/blob/345a2253984bf20b42dbc38fa968fe25f1b6f248/system/core/DB.php#L352-L353

Changing those to `self::getPdo()` would fix them, right?

**Comment by Usbac** [comment]
Fixed e38b688.
