### ISSUE TITLE
Where is the function getPublicDirectory defined?

### ISSUE THREAD

**Issue by octarino** [Usbac/wolff-framework#4]
https://github.com/Usbac/wolff-framework/blob/345a2253984bf20b42dbc38fa968fe25f1b6f248/system/utilities/Upload.php#L122

No la encuentro.

**Comment by Usbac** [comment]
Arreglado e38b688 :)

@octarino Me gustaría aprovechar tambien de darte unos agradecimientos muy especiales por el gran apoyo que le has dado al proyecto, de verdad me siento en deuda contigo. Muchísimas gracias!

**Comment by octarino** [comment]
De nada @Usbac. Te recomendaría que instalases [phpstan/phpstan](https://github.com/phpstan/phpstan) que es como encontré todas estas cosas. Suerte!
