### ISSUE TITLE
bug: variable of type PDOStatement used in string concatenation

### ISSUE THREAD

**Issue by ordago** [Usbac/wolff-framework#8]
https://github.com/Usbac/wolff-framework/blob/b3402ddb994ff53533185287d5a8892f81dd2c07/src/Core/DB.php#L334-L336

https://github.com/Usbac/wolff-framework/blob/b3402ddb994ff53533185287d5a8892f81dd2c07/src/Core/DB.php#L363-L365

https://github.com/Usbac/wolff-framework/blob/b3402ddb994ff53533185287d5a8892f81dd2c07/src/Core/DB.php#L432-L434

**Comment by Usbac** [comment]
Thank you so much for pointing that out, it has been fixed. 😄  04108ecc052328758b7cae8e3e8f0adf573f52e2
